// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc7196.kenjis_mower.subsystems;


import org.usfirst.frc7196.kenjis_mower.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.Solenoid;


/**
 * TODO: All of this
 */
public class Climb extends Subsystem {

    private Solenoid upSolenoid;
    private Solenoid downSolenoid;
    private Compressor compressor;


    public Climb() {
        // upSolenoid = new Solenoid(0, 0);
        // addChild("upSolenoid 1",upSolenoid);
        
        // downSolenoid = new Solenoid(0, 1);
        // addChild("downSolenoid", downSolenoid);

        // compressor = new Compressor(0);
        // addChild("compressor",compressor);

        // //Initialize Solenoids to be in "down" position.
        // goDown();
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
       // setDefaultCommand(new ClimbUpCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void goUp(){
        upSolenoid.set(true);
        downSolenoid.set(false);
    }

    public void goDown(){
        downSolenoid.set(true);
        upSolenoid.set(true);
    }
}

