// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc7196.kenjis_mower.subsystems;


import org.usfirst.frc7196.kenjis_mower.Robot;
import org.usfirst.frc7196.kenjis_mower.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.DigitalOutput;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import java.util.LinkedList;
import java.util.Queue;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Drive extends Subsystem {
    enum RobotDirection 
    { 
        FORWARD, BACKWARD; 
    }
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private Spark rightFront;
    private Spark rightRear;
    private SpeedControllerGroup rightMotors;
    private Spark leftFront;
    private Spark leftRear;
    private SpeedControllerGroup leftMotors;
    private DifferentialDrive diffDrive;
    private DigitalOutput frontLED, backLED;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    private RobotDirection direction;
    private Queue<Double> speedQueue;

    public Drive() {
        
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        rightFront = new Spark(4);
        addChild("rightFront",rightFront);
        rightFront.setInverted(false);
        
        rightRear = new Spark(3);
        addChild("rightRear",rightRear);
        rightRear.setInverted(false);
        
        rightMotors = new SpeedControllerGroup(rightFront, rightRear);
        addChild("rightMotors",rightMotors);
        
        
        leftFront = new Spark(1);
        addChild("leftFront",leftFront);
        leftFront.setInverted(false);
        
        leftRear = new Spark(2);
        addChild("leftRear",leftRear);
        leftRear.setInverted(false);
        
        leftMotors = new SpeedControllerGroup(leftFront, leftRear);
        addChild("leftMotors",leftMotors);
        
        
        diffDrive = new DifferentialDrive(leftMotors, rightMotors);
        addChild("diffDrive",diffDrive);
        diffDrive.setSafetyEnabled(true);
        diffDrive.setExpiration(0.1);
        diffDrive.setMaxOutput(1.0);

        frontLED = new DigitalOutput(2);
        backLED = new DigitalOutput(3);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        direction = RobotDirection.FORWARD;
        frontLED.set(true);
        backLED.set(false);
        speedQueue = new LinkedList<Double>();

        
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new Teleop());
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void setSpeed(double speed, double turn/*, double speedPercent, double turnPercent*/) {
        int directional = 1;
        if (Robot.drive.direction != RobotDirection.FORWARD)  directional = -1;
        double avgSpeed = lowPassFilter(speed);
        diffDrive.arcadeDrive(avgSpeed*directional, turn*.85, true);
    }

    //Switches the direction of the robot
    public void switchDirection() {
        if (Robot.drive.direction == RobotDirection.FORWARD) {
            direction = RobotDirection.BACKWARD;
            backLED.set(true);
            frontLED.set(false);
        }
        else {
            direction = RobotDirection.FORWARD;
            backLED.set(false);
            frontLED.set(true);

        }
    }

    //Low Pass Filter for the speed
    public double lowPassFilter(double speed) {
    	double avg = 0;
    	if(speedQueue.size() >= 12)
    	{
        	 avg = averageSpeedInQueue(speedQueue);
        	 speedQueue.remove();
    	}
        speedQueue.add(speed);
        
        return avg;
    }

    //Gets the average speed of all the values in the Queue
    public double averageSpeedInQueue(Queue<Double> queue)
    {
    	double average = 0;
    	double queueValue = 0;
    	for(int i = 0; i < 6; i++)
    	{
    		queueValue = queue.remove();
    		average += queueValue;
    		queue.add(queueValue);
    	}
    	return average/6;
    }
}

