// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc7196.kenjis_mower;

import org.usfirst.frc7196.kenjis_mower.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Joystick js1;
    public JoystickButton jsb_openGrabber, jsb_closeGrabber, jsb_intakeBall, jsb_extendFeet, jsb_retractFeet;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        //TODO: Determine button mapping for all of these
        js1 = new Joystick(0);
        //open/close disk grabber thing
        jsb_openGrabber = new JoystickButton(js1, 1);
        jsb_openGrabber.whenPressed(new OpenGrabberCommand());
        jsb_closeGrabber = new JoystickButton(js1, 2);
        jsb_closeGrabber.whenPressed(new CloseGrabberCommand());

        //activates ball intake
        jsb_intakeBall = new JoystickButton(js1, 3);
        jsb_intakeBall.whileHeld(new IntakeCommand());

        //Climb Mechanism
        jsb_extendFeet = new JoystickButton(js1, 4);
        jsb_extendFeet.whenPressed(new ClimbUpCommand());

        jsb_retractFeet = new JoystickButton(js1, 5);
        jsb_retractFeet.whenPressed(new ClimbDownCommand());

        // SmartDashboard Buttons
        //TODO: Add stuff here if there's time
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("Teleop", new Teleop());
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getjs1() {
        return js1;
    }

    //TODO: Figure out wtf goes down here
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public JoystickButton getjsb_open(){
        return jsb_openGrabber;
    }
}

